<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Overview_search-input _ngcontent-pqp-40</name>
   <tag></tag>
   <elementGuidId>d110464d-ff9a-4d43-903c-6fe200df5deb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>body > app > div > no-kennedy._ngcontent-cee-0 > div > app-bar > material-app-bar > div > div.middle._ngcontent-cee-6 > global-search > div > div > input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-input _ngcontent-pqp-40</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>300</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search by name or ID</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;content-angular-router&quot;]/app[@class=&quot;_nghost-pqp-0&quot;]/div[@class=&quot;app-container _ngcontent-pqp-0 is-using-element-scroll-host&quot;]/no-kennedy[@class=&quot;_ngcontent-pqp-0&quot;]/div[@class=&quot;_ngcontent-pqp-0&quot;]/app-bar[@class=&quot;_ngcontent-pqp-0 _nghost-pqp-5&quot;]/material-app-bar[@class=&quot;_ngcontent-pqp-5 _nghost-pqp-6&quot;]/div[@class=&quot;container _ngcontent-pqp-6&quot;]/div[@class=&quot;middle _ngcontent-pqp-6&quot;]/global-search[@class=&quot;_ngcontent-pqp-6 _nghost-pqp-40&quot;]/div[@class=&quot;search-container _ngcontent-pqp-40&quot;]/div[@class=&quot;popup-source _ngcontent-pqp-40&quot;]/input[@class=&quot;search-input _ngcontent-pqp-40&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Overview'])[1]/preceding::input[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Partners'])[1]/preceding::input[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
   </webElementXpaths>
</WebElementEntity>
