<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Test_InsertionOrder_Cer</name>
   <tag></tag>
   <elementGuidId>4b88591c-00b6-4de9-8fdd-4dc9272a39fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='0F4FF0E6-2729-419F-9AD5-4A1731CDED77--23']/div/div[2]/div/div/ol/li/ol/li/keyboard-selectable-result/div/global-search-result/div/span/highlighted-text/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-segment _ngcontent-fnw-45 segment-highlight</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Test_InsertionOrder_Cer</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;0F4FF0E6-2729-419F-9AD5-4A1731CDED77--23&quot;)/div[@class=&quot;popup _ngcontent-fnw-18&quot;]/div[@class=&quot;material-popup-content content _ngcontent-fnw-18&quot;]/div[@class=&quot;main _ngcontent-fnw-18&quot;]/div[@class=&quot;suggestion-box _ngcontent-fnw-41&quot;]/ol[@class=&quot;_ngcontent-fnw-41&quot;]/li[@class=&quot;suggestion-group-label _ngcontent-fnw-41&quot;]/ol[@class=&quot;_ngcontent-fnw-41&quot;]/li[@class=&quot;suggestion-item _ngcontent-fnw-41&quot;]/keyboard-selectable-result[@class=&quot;_ngcontent-fnw-41 _nghost-fnw-43 active&quot;]/div[@class=&quot;_ngcontent-fnw-43&quot;]/global-search-result[@class=&quot;_ngcontent-fnw-41 _nghost-fnw-44&quot;]/div[@class=&quot;_ngcontent-fnw-44&quot;]/span[@class=&quot;entity-name _ngcontent-fnw-44&quot;]/highlighted-text[@class=&quot;_ngcontent-fnw-44 _nghost-fnw-45&quot;]/span[@class=&quot;text-segment _ngcontent-fnw-45 segment-highlight&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0F4FF0E6-2729-419F-9AD5-4A1731CDED77--23']/div/div[2]/div/div/ol/li/ol/li/keyboard-selectable-result/div/global-search-result/div/span/highlighted-text/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Insertion Orders'])[1]/following::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sei_Video_Feb_Juin'])[1]/preceding::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//highlighted-text/span</value>
   </webElementXpaths>
</WebElementEntity>
