<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Identifier</name>
   <tag></tag>
   <elementGuidId>0a3488bc-9598-4c8b-8366-f99d245d88f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[placeholder=&quot;G-XXXXXXXXXX&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
