<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Table</name>
   <tag></tag>
   <elementGuidId>8c5a152b-fc8b-40e7-b7c1-26e57bea35b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>table.mat-table.mat-sort</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
