<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Loader</name>
   <tag></tag>
   <elementGuidId>ecc01559-cc28-49d5-9a84-89be32de71d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.loader</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
