<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EditPublicInventories</name>
   <tag></tag>
   <elementGuidId>43b1bdf6-9c0a-487b-9aef-140f4d37054d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>edit-fab[debugid='edit-public-inventory-sources-icon']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
